### ISSUE TITLE
What is the 'zero position'?

### ISSUE THREAD

**Issue by RobertoRoos** [jhu-dvrk/sawIntuitiveResearchKit#135]
I feel a little silly asking this, but what is the zero or home position of the PSMs, ECM and MTMs?
I was going through the calibration manual where it's mentioned many times, but I couldn't find a reference to what those positions should be exactly.

I presume for the PSMs this with the 4 tool DOFs straight, the tool slide all the way up, the arm rolled straight and the pivot all the way back. Same for the ECMs. But for the MTMs I have no clue.

Thanks. And I'm sorry if this is not the right place to ask.

**Comment by adeguet1** [comment]
Please use the dVRK slack channel for this type of question.

On Jul 7, 2021, at 07:43, Robert ***@***.******@***.***>> wrote:



I feel a little silly asking this, but what is the zero or home position of the PSMs, ECM and MTMs?
I was going through the calibration manual where it's mentioned many times, but I couldn't find a reference to what those positions should be exactly.

I presume for the PSMs this with the 4 tool DOFs straight, the tool slide all the way up, the arm rolled straight and the pivot all the way back. Same for the ECMs. But for the MTMs I have no clue.

Thanks. And I'm sorry if this is not the right place to ask.

**Comment by adeguet1** [comment]
One way to visually see where the zero position is, is to use the dVRK in simulation mode with rViz.  Try:

roslaunch dvrk_robot dvrk_arm_rviz.launch arm:=MTMR

(arm:= can be ECM, PSM1 as well)

In dVRK 2.0, you can go to the “arm” GUI tab, select “direct control” and then move the arm in joint space.

Anton


On Jul 7, 2021, at 07:43, Robert ***@***.******@***.***>> wrote:



I feel a little silly asking this, but what is the zero or home position of the PSMs, ECM and MTMs?
I was going through the calibration manual where it's mentioned many times, but I couldn't find a reference to what those positions should be exactly.

I presume for the PSMs this with the 4 tool DOFs straight, the tool slide all the way up, the arm rolled straight and the pivot all the way back. Same for the ECMs. But for the MTMs I have no clue.

Thanks. And I'm sorry if this is not the right place to ask.
