### ISSUE TITLE
Add desired robot state in dvrk-ros

### ISSUE THREAD

**Issue by jimshenzhen** [jhu-dvrk/sawIntuitiveResearchKit#20]
As discussed here:
[link to Google group](https://groups.google.com/forum/#!msg/research-kit-for-davinci/oofSD0ryN_Y/SIRyGXDQWfYJ)

**Comment by adeguet1** [comment]
I'm currently working on a significant refactoring (branch refactor).  This includes a more systematic mapping between the cisst/SAW component interfaces and the ROS topics.  The code is not ready for consumption yet but we hope to move it to the development branch in early March.  Amongst the features is a ROS topic with all state changes.

**Comment by adeguet1** [comment]
This code has now been merged in the devel branch and will be released within days.
