### ISSUE TITLE
patient_cart.launch file not found when compiling dVRK 2.3.0 as per the documentation on ROS2 Humble with Ubuntu 22.04

### ISSUE THREAD

**Issue by tushar-c** [jhu-dvrk/sawIntuitiveResearchKit#206]
My System Configuration

**OS**: Ubuntu 22.04 on WSL2 for Windows 11

**ROS Version**: ROS2 Humble

As the title suggests, I'm encountering the following issue when trying to compile the dVRK 2.3.0 (https://dvrk.readthedocs.io/en/latest/pages/software/compilation/ros2.html#testing)

Following all the steps without facing any issues up to the following command:

`ros2 launch dvrk_model patient_cart.launch generation:=Classic`

When I run the above command, I get the following error:

`file 'patient_cart.launch' was not found in the share directory of package 'dvrk_model' which is at '/home/tushar/ros2_ws/install/dvrk_model/share/dvrk_model'`

Can someone please tell me why the patient_cart.launch file is not getting imported into the concerned directory? Thanks in advance.

**Comment by adeguet1** [comment]
I don't have access to a Linux box now but can you try:
```
ros2 launch dvrk_model patient_cart.launch.py generation:=Classic
```
I think the issue comes from the missing `.py` at the end of the launch file name.

**Comment by tushar-c** [comment]
@adeguet1 thank you for your response. Replacing `patient_cart.launch` with `patient_cart.launch.py` in the above command fixed the issue for me! Maybe we can update the documentation as well regarding this.
