### ISSUE TITLE
Turn on safety relay on all boards connected

### ISSUE THREAD

**Issue by adeguet1** [jhu-dvrk/sawIntuitiveResearchKit#21]
Can we turn on the safety relays on all boards connected to the firewire bus instead of just those used in mtsRobotIO1394?  This way we could avoid re-wiring the e-stops everytime.   This probably requires some changes in AmpIO?

**Comment by pkazanzides** [comment]
Should be simple to do.  The FirewirePort object knows about all boards connected on the bus.  So, in WriteAllBoards, you could issue quadlet writes to the other boards to set the safety relays the same way as the configured boards.

**Comment by adeguet1** [comment]
We provide the command line tool `qlacommand -c close-relays` to close the safety relays before starting the application.
