### ISSUE TITLE
Gravity compensation for master arm

### ISSUE THREAD

**Issue by adeguet1** [jhu-dvrk/sawIntuitiveResearchKit#3]
The current implementation relies on cisstRobot robManipulator which can handle some gravity compensation (position and inertia matrix along serial links).  At that point, we don't have an automatic way to identify these parameters.   Furthermore, there are some forces on the master arm that can be taken into account using the robManipulator model (e.g. cable tension on first axis, ...) so we'll probably need some custom code in the mtsMTM class.

**Comment by pkazanzides** [comment]
MTM gravity compensation (contributed by CUHK) is in Release 1.7.0.
