### ISSUE TITLE
psm.close_jaw() function doesn't work in devel branch

### ISSUE THREAD

**Issue by zrwang** [jhu-dvrk/sawIntuitiveResearchKit#72]
Hi Anton,

The close_jaw() function in Matlab wrapper doesn't work properly on my side. I updated the software environment to the latest versions on devel branch. I checked commit history, and it seems that you changed function `mtsIntuitiveResearchKitPSM::SetJawPosition`. Is that possible it's related to this?

Thanks!
Zerui

**Comment by adeguet1** [comment]
It’s a known bug (at least for me) and I’m working on a fix before next release.   There’s a workaround for now, i.e. force the control mode to switch using a move command without any effect (i.e. move to current position).   I wrote some scripts to test/debug the dVRK stack mote systematically and the work around in show in Python:
https://github.com/jhu-dvrk/dvrk-ros/blob/devel/dvrk_python/scripts/dvrk_psm_test.py#L56

And Matlab:
https://github.com/jhu-dvrk/dvrk-ros/blob/devel/dvrk_matlab/test/test_psm_api.m#L13

I hope to fix this later this week.  We shouldn’t have to do a “dummy” move command for the jaw commands to work.

Anton


---
Anton Deguet
www.lcsr.jhu.edu - www.malonecenter.jhu.edu

**Comment by zrwang** [comment]
Thank you for your information! Let me know if I can help.

Best regards,
Zerui

**Comment by adeguet1** [comment]
Fixed in 1.5
